### ISSUE TITLE
eliminar comentarios

### ISSUE THREAD

**Issue by Nidev-lab** [rdanielpolich/serverbills#3]
Buenas! como va? encontre algunos comentarios en el codigo que deben eliminar.

![image](https://user-images.githubusercontent.com/53904695/195881989-9e3fa730-77d8-4d22-9c60-5154094ed5f5.png)

en si, los comentarios en el codigo no son una buena practica, pero  el codigo comentado es mucho menos aceptado.

Cualquier cosita podes contactarme a [nicogonzalez2008@gmail.com](mailto:nicogonzalez2008@gmail.com) o por el slack de RollingCode

**Comment by rdanielpolich** [comment]
hola buenas, perfecto, gracias por el aporte
